trades:
  symbols:
    - "BTC/EUR"
    - "ETH/EUR"
  frequency: "0 23 * * *"
  intervals:
    - 1
    - 5
    - 15
    - 30

spring:
  data:
    mongodb:
      database: watcher
      port: 27017
      host: localhost
